name: Download Excel Sheet

# This workflow runs on push events to the main branch
on:
  push:
    branches: [main]

# Jobs to be executed in the workflow
jobs:
  download_excel:
    runs-on: ubuntu-latest  # Replace with your preferred runner OS

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Use Node.js version 20
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies (assuming Node.js)
      - name: Install dependencies
        run: npm install  # Adjust if you use a different package manager

      # Download data and generate Excel sheet
      - name: Download and create Excel
        run: |
          tsc script.ts
          node script.js  # Replace with your script filename
        env:
          API_URL: 'https://jsonplaceholder.typicode.com/todos/1'  # Replace with your actual API URL

      # Set current date as an environment variable
      - name: Set current date
        id: current_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Rename the output file to include the current date
      - name: Rename output file
        run: mv my_data.xlsx ${{ steps.current_date.outputs.date }}.xlsx

      # Upload generated Excel file as an artifact
      - name: Upload Excel file
        uses: actions/upload-artifact@v3
        with:
          name: excel-data
          path: ${{ runner.workspace }}/${{ steps.current_date.outputs.date }}.xlsx
