name: Download Excel Sheet

# This workflow runs on push events to the main branch
on:
  push:
    branches: [ main ]

# Jobs to be executed in the workflow
jobs:
  download_excel:
    runs-on: ubuntu-latest  # Replace with your preferred runner OS

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install dependencies (assuming Node.js)
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install  # Adjust if you use a different package manager

      # Download data and generate Excel sheet
      - name: Download and create Excel
        run: |
          node script.ts  # Replace with your script filename
        env:
          API_URL: 'https://jsonplaceholder.typicode.com/todos/1'  # Replace with your actual API URL

      # Upload generated Excel file as an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: excel-data
          path: my_data.xlsx  # Replace with your output filename

